# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-05 18:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpartaActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Sparta Activities',
                'verbose_name': 'Sparta Activity',
            },
        ),
        migrations.CreateModel(
            name='SpartaGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=140, verbose_name='Name')),
                ('status', models.IntegerField(choices=[(1, 'inactive'), (0, 'active')], default=1)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sparta.SpartaActivity')),
            ],
            options={
                'verbose_name_plural': 'Groups',
                'verbose_name': 'Group',
            },
        ),
        migrations.CreateModel(
            name='SpartaMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('role', models.IntegerField(choices=[(0, 'tutor'), (1, 'learner')])),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sparta.SpartaGroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='spartamembership',
            unique_together=set([('user', 'group', 'role')]),
        ),
        migrations.AlterUniqueTogether(
            name='spartagroup',
            unique_together=set([('name', 'activity')]),
        ),
    ]
