# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-31 19:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sparta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spartagroup',
            name='members',
            field=models.ManyToManyField(related_name='sparta_groups', through='sparta.SpartaMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='spartagroup',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='sparta.SpartaActivity'),
        ),
        migrations.AlterField(
            model_name='spartagroup',
            name='name',
            field=models.CharField(blank=True, max_length=140, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='spartamembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sparta.SpartaGroup'),
        ),
        migrations.AlterField(
            model_name='spartamembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
